export const sentenceList = [
  { word: "do homework", image: "https://openmoji.org/data/color/svg/1F4DD.svg" },
  { word: "do housework", image: "https://openmoji.org/data/color/svg/1F9F9.svg" },
  { word: "watch TV", image: "https://openmoji.org/data/color/svg/1F4FA.svg" },
  { word: "read books", image: "https://openmoji.org/data/color/svg/1F4D6.svg" },
  { word: "cook the meals", image: "https://openmoji.org/data/color/svg/1F373.svg" },
  { word: "water the flowers", image: "https://openmoji.org/data/color/svg/1F33C.svg" },
  { word: "sweep the floor", image: "https://openmoji.org/data/color/svg/1F9F9.svg" },
  { word: "clean the bedroom", image: "https://openmoji.org/data/color/svg/1F9F9.svg" },
  { word: "make the bed", image: "https://openmoji.org/data/color/svg/1F6CF.svg" },
  { word: "do morning exercises", image: "https://openmoji.org/data/color/svg/1F3CB.svg" },
  { word: "eat breakfast", image: "https://openmoji.org/data/color/svg/1F373.svg" },
  { word: "eat dinner", image: "https://openmoji.org/data/color/svg/1F37D.svg" },
  { word: "go to school", image: "https://openmoji.org/data/color/svg/1F3EB.svg" },
  { word: "have English class", image: "https://openmoji.org/data/color/svg/1F4DA.svg" },
  { word: "play sports", image: "https://openmoji.org/data/color/svg/26BD.svg" },
  { word: "get up", image: "https://openmoji.org/data/color/svg/1F4AA.svg" },
  { word: "climb mountains", image: "https://openmoji.org/data/color/svg/1F3D4.svg" },
  { word: "go shopping", image: "https://openmoji.org/data/color/svg/1F6CD.svg" },
  { word: "play the piano", image: "https://openmoji.org/data/color/svg/1F3B9.svg" },
  { word: "go hiking", image: "https://openmoji.org/data/color/svg/1F6B5.svg" },
  { word: "fly kites", image: "https://openmoji.org/data/color/svg/1FA81.svg" },
  { word: "make a snowman", image: "https://openmoji.org/data/color/svg/26C4.svg" },
  { word: "plant trees", image: "https://openmoji.org/data/color/svg/1F333.svg" },
  { word: "draw", image: "https://openmoji.org/data/color/svg/1F58C.svg" },
  { word: "read a book", image: "https://openmoji.org/data/color/svg/1F4D6.svg" },
  { word: "answer the phone", image: "https://openmoji.org/data/color/svg/1F4DE.svg" },
  { word: "listen to music", image: "https://openmoji.org/data/color/svg/1F3B5.svg" },
  { word: "clean the room", image: "https://openmoji.org/data/color/svg/1F9F9.svg" },
  { word: "write a letter", image: "https://openmoji.org/data/color/svg/1F4DD.svg" },
  { word: "write an e-mail", image: "https://openmoji.org/data/color/svg/1F4E7.svg" },
  { word: "drink water", image: "https://openmoji.org/data/color/svg/1F4A7.svg" },
  { word: "take pictures", image: "https://openmoji.org/data/color/svg/1F4F7.svg" },
  { word: "watch insects", image: "https://openmoji.org/data/color/svg/1FAB2.svg" },
  { word: "pick up leaves", image: "https://openmoji.org/data/color/svg/1F343.svg" },
  { word: "Good morning", image: "https://openmoji.org/data/color/svg/1F305.svg" },
  { word: "Good afternoon", image: "https://openmoji.org/data/color/svg/2600.svg" },
  { word: "Good evening", image: "https://openmoji.org/data/color/svg/1F307.svg" },
  { word: "Good night", image: "https://openmoji.org/data/color/svg/1F319.svg" },
  { word: "Hello", image: "https://openmoji.org/data/color/svg/1F44B.svg" },
  { word: "Hi", image: "https://openmoji.org/data/color/svg/1F44B.svg" },
  { word: "Thank you", image: "https://openmoji.org/data/color/svg/1F64F.svg" },
  { word: "You're welcome", image: "https://openmoji.org/data/color/svg/1F60A.svg" },
  { word: "Excuse me", image: "https://openmoji.org/data/color/svg/1F647.svg" },
  { word: "Sorry", image: "https://openmoji.org/data/color/svg/1F614.svg" },
  { word: "See you", image: "https://openmoji.org/data/color/svg/1F44B.svg" },
  { word: "Bye", image: "https://openmoji.org/data/color/svg/1F44B.svg" }
]; 